function [fitresult, gof] = createFitParam(VarName2, VarName1)
%createFitParam(Pressure,Distance)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : VarName2
%      Y Output: VarName1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Oct-2015 16:22:06


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( VarName2, VarName1 );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 7.98461849311654e-13;     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'VarName1 vs. VarName2', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'VarName2' );
ylabel( 'VarName1' );
grid on


